export enum LayerEvent {
  mousedown = 'mousedown',
  mouseup = 'mouseup',
  click = 'click',
  dblclick = 'dblclick',
  mousemove = 'mousemove',
  mouseover = 'mouseover',
  mouseenter = 'mouseenter',
  mouseleave = 'mouseleave',
  mouseout = 'mouseout',
  contextmenu = 'contextmenu',
}

export enum SceneEvent {
  loaded = 'loaded',
  mapMove = 'mapmove',
  moveStart = 'movestart',
  moveEnd = 'moveend',
  zoomChange = 'zoomchange',
  zoomStart = 'zoomstart',
  zoomEnd = 'zoomend',
  click = 'click',
  dblclick = 'dblclick',
  mousemove = 'mousemove',
  mousewheel = 'mousewheel',
  mouseover = 'mouseover',
  mouseout = 'mouseout',
  mouseup = 'mouseup',
  mousedown = 'mousedown',
  contextmenu = 'contextmenu',
  dragstart = 'dragstart',
  dragging = 'dragging',
  dragend = 'dragend',
}
